# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'tv' do
pod 'LGSideMenuController', '~> 1.0.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'MBProgressHUD', '~> 0.9'
pod 'Reachability', '~> 3.2'
pod 'ZAlertView', '~> 0.1'
pod 'Haneke', '~> 1.0'
end

